### ISSUE TITLE
Error: "Promise is not defined"

### ISSUE THREAD

**Issue by spekulatius** [vekexasia/mysqldumpsplit#1]
Hello,

I have got the following error:

xxx@xxx /var/www/xxxxxx (release) $ mysqldumpsplit database.sql
Starting :)
[ReferenceError: Promise is not defined]

cheers,
Peter

**Comment by vekexasia** [comment]
hmm? whihch version of node are you running on?

**Comment by spekulatius** [comment]
$ node -v
v6.2.1

**Comment by vekexasia** [comment]
@spekulatius sorry for the bad delay of my answer but I'm currently using it on several machines node 4 and 6. 

Are you still suffering this issue?

**Comment by spekulatius** [comment]
Hello @vekexasia 

all good. I've upgraded my OS by now and can't really replicate the issue. I'll try it again next time and let you know if I find any problems.

Peter
